export const MOCK_JOBS = [
  {
    id: "1",
    title: "Quantitative Research Intern",
    company: "Jane Street",
    location: "New York, NY",
    url: "https://example.com/j1",
    source: "career_page",
    postedAt: new Date("2025-02-01"),
    deadline: null,
    description: "Quant intern role...",
    skills: ["Python", "C++", "statistics"],
    visaFlag: false,
    relevanceScore: 92,
    relevanceReason: "Strong fit for quant research; your Monte Carlo and ML experience align well. F1 + EU citizen noted; no visa penalty for this role.",
    status: "DISCOVERED",
  },
  {
    id: "2",
    title: "Fusion Energy Intern",
    company: "Commonwealth Fusion Systems",
    location: "Cambridge, MA",
    url: "https://example.com/j2",
    source: "simplify",
    postedAt: new Date("2025-02-10"),
    deadline: new Date("2025-03-15"),
    description: "Plasma and fusion...",
    skills: ["Python", "physics", "simulation"],
    visaFlag: false,
    relevanceScore: 88,
    relevanceReason: "ITER and PPPL experience are directly relevant. CFS focuses on tokamak; your JAX digital twin work is a strong match.",
    status: "DISCOVERED",
  },
  {
    id: "3",
    title: "Software Engineering Intern",
    company: "Two Sigma",
    location: "New York, NY",
    url: "https://example.com/j3",
    source: "github_repo",
    postedAt: new Date("2025-02-05"),
    deadline: null,
    description: "SWE intern...",
    skills: ["Python", "Java", "distributed systems"],
    visaFlag: true,
    relevanceScore: 65,
    relevanceReason: "Role fit is good; description mentions US work authorization without sponsorship — flagged for your awareness.",
    status: "DISCOVERED",
  },
  {
    id: "4",
    title: "Physical AI / Robotics Intern",
    company: "Physical Intelligence",
    location: "San Francisco, CA",
    url: "https://example.com/j4",
    source: "linkedin",
    postedAt: new Date("2025-02-12"),
    deadline: null,
    description: "Embodied AI, robotics...",
    skills: ["Python", "reinforcement learning", "simulation"],
    visaFlag: false,
    relevanceScore: 85,
    relevanceReason: "Virturoid and simulation experience align well with physical AI. RL and robotics focus match your background.",
    status: "DISCOVERED",
  },
  {
    id: "5",
    title: "Research Scientist Intern",
    company: "DeepMind",
    location: "London, UK",
    url: "https://example.com/j5",
    source: "levels_fyi",
    postedAt: new Date("2025-02-08"),
    deadline: null,
    description: "Research intern...",
    skills: ["Python", "ML", "research"],
    visaFlag: false,
    relevanceScore: 78,
    relevanceReason: "EU-based role; no visa penalty. Your published work and research experience are relevant.",
    status: "DISCOVERED",
  },
  {
    id: "6",
    title: "HPC / Simulation Intern",
    company: "TAE Technologies",
    location: "Irvine, CA",
    url: "https://example.com/j6",
    source: "indeed",
    postedAt: new Date("2025-02-03"),
    deadline: null,
    description: "HPC, plasma simulation...",
    skills: ["C++", "HPC", "Python"],
    visaFlag: false,
    relevanceScore: 82,
    relevanceReason: "Fusion and simulation focus match your PPPL and JAX digital twin work. HPC and scientific computing are a fit.",
    status: "DISCOVERED",
  },
];
