export const USER_PROFILE = {
  name: "Hari",
  school: "Georgia Institute of Technology",
  major: "Computer Science (Intelligence + Modeling/Simulation) + Physics Minor",
  gradYear: 2028,
  gpa: 3.81,
  visaStatus: "F1",
  euCitizen: true,
  targetRoles: [
    "Quantitative Research Intern",
    "Quantitative Trading Intern",
    "Software Engineering Intern",
    "Computational Physics Intern",
    "Fusion Energy / Plasma Physics Intern",
    "Robotics Software Engineer Intern",
    "Physical AI / Embodied AI Intern",
    "Data Science Intern",
    "Machine Learning Intern",
    "Scientific Computing Intern",
    "Research Scientist Intern",
    "HPC / Simulation Intern",
  ],
  keywords: [
    "quant",
    "trading",
    "plasma",
    "fusion",
    "tokamak",
    "MHD",
    "JAX",
    "simulation",
    "digital twin",
    "robotics",
    "embodied AI",
    "physical AI",
    "computational physics",
    "HPC",
    "scientific computing",
    "machine learning",
    "reinforcement learning",
    "C++",
    "Python",
    "numerical methods",
    "Monte Carlo",
  ],
  blacklist: [
    "US citizenship required",
    "security clearance",
    "TS/SCI",
    "must be authorized to work in the US without sponsorship",
  ],
  targetFirms: [
    "Jane Street",
    "Five Rings Capital",
    "HRT",
    "Flow Traders",
    "Citadel",
    "DE Shaw",
    "Two Sigma",
    "Jump Trading",
    "Optiver",
    "Virtu",
    "Commonwealth Fusion Systems",
    "TAE Technologies",
    "Pacific Fusion",
    "Helion Energy",
    "MIT PSFC",
    "PPPL",
    "ITER",
    "Physical Intelligence",
    "Boston Dynamics",
    "Figure",
    "1X Technologies",
    "Perplexity AI",
    "Anthropic",
    "DeepMind",
    "Google DeepMind",
    "SpaceX",
    "Relativity Space",
    "Joby Aviation",
    "Janus Henderson",
    "Point72",
    "Millennium",
  ],
  keyExperienceHighlights: [
    "Youngest-ever intern at ITER science division in France at age 17, built internationally deployed analysis tools",
    "Youngest researcher selected for 17th Fusion Kudowa Summer School in Poland at age 16, presented original research on pulsed fusion propulsion",
    "Research at Princeton Plasma Physics Laboratory on spin-polarized fusion and Field-Reversed Configuration plasmas",
    "Published work on dark matter MCMC analysis",
    "Built Virturoid: an AI-powered robot generation system",
    "Built comprehensive portfolio management app with ML signal finding, sentiment analysis, and Monte Carlo simulation",
    "Currently building JAX-based digital twin frameworks for tokamak plasma systems with Dr. Qi Tang at Georgia Tech",
  ],
} as const;

export type UserProfile = typeof USER_PROFILE;
